name: heroku-deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-heroku:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: heroku deploy
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alectrion-2023-1"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            GATEWAY_URL
        env:
          GATEWAY_URL: ${{ secrets.GATEWAY_URL }}
